### PR TITLE
Add Vehicle Presence Support

### PR DESCRIPTION
**Pull request by therivenman**
Just got my OpenGarage a week ago, and I love how flexible the unit is.  Found this plugin, and have been enjoying using it, so I took a stab at implementing vehicle presence.  I've been using this feature for a few days and it's been working well.

* Address Issue  #8
* Add occupancy sensor service to OpenGarage class.
* Only shows vehicle occupancy when garage door is closed.  Appears unoccupied when door is up.
---
IMG_6658D807E4BB-1
IMG_91DF1B47B4E8-1
Screen Shot 2020-08-11 at 10 51 20 PM

### CODE REVIEW

**Comment by therivenman** [comment]
I’d just like to add that if a user doesn’t choose to use this feature, they can leave the home tile combined, and they will only see it when they enter the detailed view. You can also choose to split the tiles as you can see in the attached photos.

**Review by salbahra — APPROVED** [review]

**Comment by salbahra** [comment]
Thank you for the PR, excited to try this out!

**Comment by therivenman** [comment]
No problem.  Glad to be able to help out.

**Comment by gondalez** [comment]
I second this thank you :) 
Any chance of an npm release so I can try it out? 🙏

**Comment by gondalez** [comment]
@salbahra any chance of publishing to npm? 🙏  🚗  :)

**Comment by salbahra** [comment]
Sorry for the delay but yes this has been published now!

**Comment by gondalez** [comment]
Thanks, updated and working well 👍

**Pull request merged**
