### PR TITLE
Configurable polling, improved target-state logic, and unit tests

### PR DESCRIPTION
**Pull request by timcharper**
This is a monster pull request. I've been running my fork for the past week and it has worked much better. Notable changes:

- Target state is more intelligent as we now use OpenGarage firmware 1.0.8's support for setting target state. This fixes issue https://github.com/OpenGarage/homebridge-og/issues/4
- Initial state is properly reported when HomeBridge restart and Home is already open on an iOS device. Fixes issue #5.
- Configurable polling now introduced. Previously, garage state was only queried when the home app was opened. Now, the state is polled and pushed to Home so that notifications can happen.
- Improved target state transition logic. I introduced a configurable time window in which the garage door state change that was initiated should be reliably observed by sensor. If it fails to reach this state, it rolls back to the previous target (target = current). This improves how the state change looks in the app.
- Unit tests! Helpful as it is difficult to justify opening and closing your garage door over and over just so you can teat the code.

### CODE REVIEW

**Comment by salbahra** [comment]
Thank you very much for this awesome contribution! The code changes look great but I won’t have time to test until Monday so I will hold off on merging until then.

Thanks again!

**Comment by timcharper** [comment]
Hey @salbahra ! Curious if you were able to install / had any success here. BTW I've loved my OpenGarage. (and my OpenSprinkler lol).

**Comment by salbahra** [comment]
Finally got around to testing this, works great!! Thanks again!

**Comment by salbahra** [comment]
Just to follow up, it's been a week now and this is running perfectly! I get notifications with Home now consistently and reliably. This also solved an issue where more than one OpenGarage was present in a home.

Thanks again!!!

**Pull request merged**
